### ISSUE TITLE
Error at install, in omv-salt deploy run omvextras

### ISSUE THREAD

**Issue by jok2** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#28]
I tried to install the OMVExtras Repository on a fresh installed OMV 5.0.5 (+ Updates).
I got the following error:

wget -O - http://omv-extras.org/install | bash
...

2019-08-27 00:51:06 (1,62 MB/s) - »openmediavault-omvextrasorg_latest_all5.deb« gespeichert [63216/63216]

(Lese Datenbank ... 44281 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von openmediavault-omvextrasorg_latest_all5.deb ...
Entpacken von openmediavault-omvextrasorg (5.0.4) über (5.0.4) ...
openmediavault-omvextrasorg (5.0.4) wird eingerichtet ...
Updating configuration database ...
dpkg: Fehler beim Bearbeiten des Paketes openmediavault-omvextrasorg (--install):
 »installiertes openmediavault-omvextrasorg-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück
Trigger für openmediavault (5.0.5-1) werden verarbeitet ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
Fehler traten auf beim Bearbeiten von:
 openmediavault-omvextrasorg

######################################
The error seems to be in the oms-salt deploy run omvextras step:

omv-salt deploy run omvextras

debian:
----------
          ID: configure_apt_sources_list_omvextras
    Function: file.managed
        Name: /etc/apt/sources.list.d/omvextras.list
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 01:03:43.319154
    Duration: 73.327 ms
     Changes:
----------
          ID: configure_apt_pref_omvextras
    Function: file.managed
        Name: /etc/apt/preferences.d/omvextras.pref
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 01:03:43.392761
    Duration: 6.294 ms
     Changes:
----------
          ID: refresh_database_apt
    Function: module.run
        Name: pkg.refresh_db
      Result: True
     Comment:
     Started: 01:03:43.400385
    Duration: 0.725 ms
     Changes:

Summary for debian
------------
Succeeded: 1
Failed:    2
------------
Total states run:     3
Total run time:  80.346 ms

###################################

i've got no experience with saltstack and couldn't find a way to get past this error.
i compared the default.sls with e.g. the apt/defaults.sls and couldn't find an obvious difference.

**Comment by jok2** [comment]
it is a TerraMaster F4-220, a NAS System with a J1800, 4GB, a small SSD.

I used this article to install it on the ssd:
https://www.bachmann-lan.de/terramaster-f2-220-nas-mit-openmediavault/

After the first boot i did some basic configuration like setting up NTP and doing an upgrade (via web interface ). OMV version is now 5.0.5-1
I have now removed the not finished install of openmediavault-omvextrasorg.

the output of apt-get update:
root@openmediavault:~# apt-get update
Holen:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Holen:2 file:/var/cache/openmediavault/archives  Release
Ign:2 file:/var/cache/openmediavault/archives  Release
Holen:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Holen:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Ign:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Holen:5 file:/var/cache/openmediavault/archives  Translation-en
Ign:5 file:/var/cache/openmediavault/archives  Translation-en
Holen:6 file:/var/cache/openmediavault/archives  Translation-de
Ign:6 file:/var/cache/openmediavault/archives  Translation-de
Holen:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Holen:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Ign:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Holen:5 file:/var/cache/openmediavault/archives  Translation-en
Ign:5 file:/var/cache/openmediavault/archives  Translation-en
Holen:6 file:/var/cache/openmediavault/archives  Translation-de
Ign:6 file:/var/cache/openmediavault/archives  Translation-de
Holen:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Holen:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Ign:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Holen:5 file:/var/cache/openmediavault/archives  Translation-en
Ign:5 file:/var/cache/openmediavault/archives  Translation-en
Holen:6 file:/var/cache/openmediavault/archives  Translation-de
Ign:6 file:/var/cache/openmediavault/archives  Translation-de
Holen:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Holen:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Ign:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Holen:5 file:/var/cache/openmediavault/archives  Translation-en
Ign:5 file:/var/cache/openmediavault/archives  Translation-en
Holen:6 file:/var/cache/openmediavault/archives  Translation-de
Ign:6 file:/var/cache/openmediavault/archives  Translation-de
Holen:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Holen:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Ign:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Holen:5 file:/var/cache/openmediavault/archives  Translation-en
Ign:5 file:/var/cache/openmediavault/archives  Translation-en
Holen:6 file:/var/cache/openmediavault/archives  Translation-de
Ign:6 file:/var/cache/openmediavault/archives  Translation-de
Holen:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Holen:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Ign:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Holen:5 file:/var/cache/openmediavault/archives  Translation-en
Ign:5 file:/var/cache/openmediavault/archives  Translation-en
Holen:6 file:/var/cache/openmediavault/archives  Translation-de
Ign:6 file:/var/cache/openmediavault/archives  Translation-de
Holen:3 file:/var/cache/openmediavault/archives  Packages
Holen:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Ign:4 file:/var/cache/openmediavault/archives  Translation-de_DE
Holen:5 file:/var/cache/openmediavault/archives  Translation-en
Ign:5 file:/var/cache/openmediavault/archives  Translation-en
Holen:6 file:/var/cache/openmediavault/archives  Translation-de
Ign:6 file:/var/cache/openmediavault/archives  Translation-de
OK:7 http://packages.openmediavault.org/public usul InRelease
OK:8 http://deb.debian.org/debian buster InRelease
OK:9 http://security.debian.org/debian-security buster/updates InRelease
OK:10 http://deb.debian.org/debian buster-updates InRelease
OK:11 https://openmediavault.github.io/packages usul InRelease
OK:12 http://cdn-fastly.deb.debian.org/debian buster-backports InRelease
Paketlisten werden gelesen... Fertig

the output of dpkg -l | grep openm
ii  openmediavault                  5.0.5-1                     all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring          1.0                         all          GnuPG archive keys of the OpenMediaVault archive

**Comment by jok2** [comment]
I tried the install again, first in th evirtual machine from which i created the ssd image.
it worked.
then i tried it again in the TerraMaster. And it worked also.
No idea what changed overnight, but i can install the extras plugins now.

**Comment by drajar** [comment]
The problem is not solved.

+ case "$1" in
+ dpkg-trigger update-fixperms
+ dpkg-trigger update-locale
+ echo 'Updating configuration database ...'
Updating configuration database ...
+ omv-confdbadm create conf.system.omvextras
+ '[' -n 4.1.16 ']'
+ omv-confdbadm migrate conf.system.omvextras 4.1.16
  Running migration conf.system.omvextras_5.0.4
  Running migration conf.system.omvextras_5.1
+ omv-salt deploy run --quiet omvextras
dpkg: error processing package openmediavault-omvextrasorg (--configure):
 installed openmediavault-omvextrasorg package post-installation script subproce                                                                                                                                                             ss returned error exit status 1

and

root@omv:~# omv-salt deploy run omvextras
omv.dynamicpuzzle.ro:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.omvextras.default' failed: Jinja error: The p                                                                                                                                                             roperty 'repos.repo.uuid' does not exist in the model 'conf.system.omvextras'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 393, in re                                                                                                                                                             nder_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in rend                                                                                                                                                             er
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in ren                                                                                                                                                             der
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in hand                                                                                                                                                             le_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 18, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get
    objs = db.get(id_, identifier)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line                                                                                                                                                              85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line                                                                                                                                                              709, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line                                                                                                                                                              470, in _elements_to_object
    result.set_dict(self._element_to_dict(elements[0]), False)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 20                                                                                                                                                             7, in set_dict
    self.set(key, value, validate)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 18                                                                                                                                                             1, in set
    self.assert_exists(name)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 15                                                                                                                                                             3, in assert_exists
    % (name, self.model.id)
openmediavault.exceptions.AssertException: The property 'repos.repo.uuid' does n                                                                                                                                                             ot exist in the model 'conf.system.omvextras'.

; line 18

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

{% set config = salt['omv_conf.get']('conf.system.omvextras') %}    <===========                                                                                                                                                             ===========
{% set use_kernel_backports = salt['pillar.get']('default:OMV_APT_USE_KERNEL_BAC                                                                                                                                                             KPORTS', True) -%}

configure_apt_sources_list_omvextras:
  file.managed:
    - name: "/etc/apt/sources.list.d/omvextras.list"
[...]
---

**Comment by ryecoaaron** [comment]
@drajar The problem isn't with the plugin.  It doesn't support upgrades.  The fact that you still have the 4.1.16 migration script means you are trying to upgrade.  Remove omv-extras and re-install using the install script

**Comment by drajar** [comment]
Yes @ryecoaaron , apt-get purge and install using script solved the problem. Thx.

**Comment by flori-uni** [comment]
I'm getting the same problem, but I don't have installed an old version anymore. Is there any possible workaround getting the omvextras working again?

**Comment by ryecoaaron** [comment]
What is the "same problem"?
