### ISSUE TITLE
mitigate sunset of JFrog Bintray on 1May2021 

### ISSUE THREAD

**Issue by mi-hol** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#49]
Currently the list of plugin is hosted on JFrog BinTray, but BinTray will become obsoleted 1May2021
[JFrog Announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

Would github be a feasible replacement?

**Comment by ryecoaaron** [comment]
I am well aware of this.  Once I find a new place for the repos (omv-extras has been self-hosted before but github will be the likely location), this will be a transparent change for users.  Documentation will not need to be updated since nothing other than the plugin is using bintray.  Once a user updates omv-extras, it will just start using the new repo.  I have a lot of automation that is specifically built for bintray that needs to be updated.  No need to track this in an issue.
