### ISSUE TITLE
Portainer: add option to define agent secret

### ISSUE THREAD

**Issue by fane32** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#83]
Please add the option in OMV dashboard to add / configure the docker environment variable "AGENT_SECRET" to portainer. 
The possibility to set this container environment variable is very helpfull, when you want to use this portainer instance to control also other docker environments in your network where a portainer-agent is running.

Thank you very much!

**Comment by ryecoaaron** [comment]
Since almost all users don't need this, I don't want to add this.  omv-extras adds portainer just to be helpful and won't support everything.  If you need a more complicated install, install the compose plugin and use the portainer template in the Files tab.  Then you can customize the docker-compose file with anything you need.
